dataset: MNIST
device: [0]

ipc: 1000
syn_steps: 80
expert_epochs: 2
lr_img: 0.1
lr_teacher: 0.01
buffer_path: ../buffer/buffers/
data_path: ../dataset/
ema_decay: 0.9995
Iteration: 10
batch_syn: 256

# wandb
project: MNIST_ipc10

num_eval: 100
eval_it: 100
skip_first_eva: True

lr_y: 2.
Momentum_y: 0.9
threshold: 1.
pix_init: real
batch_train: 256

min_start_epoch: 0
current_max_start_epoch: 10
max_start_epoch: 20
expansion_end_epoch: 1000

lr_lr: 0.00001
zca: False

